version: '2.1'
services:
  ss_interface_soap:
    container_name: docker_interface_soap
    build:
      context: .
      dockerfile: Dockerfile-Soap
    environment:
      PORT: '6060'
    ports:
      - '6060:6060'
  ss_interface_rest:
    container_name: docker_interface_rest
    build:
      context: .
      dockerfile: Dockerfile-Rest
    environment:
      PORT: '9090'
    ports:
      - '9090:9090'